services:
  - type: web
    name: vaibhava-tech-website
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
