name = "vaibhava-tech-website"
compatibility_date = "2024-09-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "vaibhava-tech-leads"
database_id = "6786bf73-021e-4536-b972-ae98f2ef2e3c"
