export const companyContent = {
  name: 'Vaibhava Tech',
  tagline: 'Engineering the Future Through Convergent Technology',
  techStack: ['AI', 'XR', 'Web', 'Cloud', 'Robotics', 'STEM', 'Data'],
  sectors: [
    'Agriculture',
    'Education',
    'Industry',
    'Defence',
    'Research',
    'Enterprise',
  ],
  focusAreas: [
    {
      title: 'Artificial Intelligence & AI-powered applications',
      description: 'Smarter solutions for a better tomorrow',
      icon: 'ai',
      image: 'focus-ai.jpg',
      link: '/solutions',
    },
    {
      title: 'Extended Reality (XR) – VR, AR & MR',
      description: 'Immersive experiences for real world impact',
      icon: 'xr',
      image: 'focus-xr.jpg',
      link: '/solutions/xr',
    },
    {
      title: 'Web and Cloud Technologies',
      description: 'Scalable, secure and connected platforms',
      icon: 'web',
      image: 'focus-web.jpg',
      link: '/solutions',
    },
    {
      title: 'Enterprise Software',
      description: 'Digital solutions to streamline your business',
      icon: 'enterprise',
      image: 'enterprise-hologram.jpg',
      link: '/solutions/enterprise',
    },
    {
      title: 'Agriculture Technology',
      description: 'Innovative solutions for a sustainable future',
      icon: 'agriculture',
      image: 'focus-agriculture.jpg',
      link: '/solutions/agriculture',
    },
    {
      title: 'Robotics & STEM Technology',
      description: 'Bridging innovation with real world applications',
      icon: 'robotics',
      image: 'focus-robotics.jpg',
      link: '/solutions/education',
    },
    {
      title: 'Digital Simulation and Immersive Learning',
      description: 'Hands-on learning in a virtual world',
      icon: 'simulation',
      image: 'vision-explore.jpg',
      link: '/solutions/education',
    },
  ],
};
